[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

# Disable the problematic Next.js plugin
[plugins]
  disabled = ["@netlify/plugin-nextjs"]

# Redirect rules for static site
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200