[build]
  command = "node build-static.js"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

# Redirect rules for static site
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
