[build]
  command = "node build-static.js"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

# Explicitly disable framework detection and all plugins
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Disable all plugins to prevent auto-detection
[plugins]
  disabled = ["@netlify/plugin-nextjs", "@netlify/plugin-lighthouse", "netlify-plugin-cloudinary"]

# Redirect rules for static site
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
